---

name: HashiCorp Sentinel

on:
  push:

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: test
        uses: volcano-coffee-company/setup-sentinel@v1
        with:
          version: '0.13'
      - run: sentinel test
