---

name: HashiCorp Sentinel

on:
  push:

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: test
        uses: docker://alpine:3.8
        run: |
          curl --location --output sentinel.zip https://releases.hashicorp.com/sentinel/0.18.4/sentinel_0.18.4_linux_amd64.zip
          unzip sentinel.zip
          chmod +x sentinel
          sentinel
